#include<bits/stdc++.h>
using namespace std;
int main()
{
    char st[100000];
    while(cin.getline(st, 100000)){
        int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0,w=0,x=0,y=0,z=0,A=0,B=0,C=0,D=0,E=0,F=0,G=0,H=0,I=0,J=0,K=0,L=0,M=0,N=0,O=0,P=0,Q=0,R=0,S=0,T=0,U=0,V=0,W=0,X=0,Y=0,Z=0;
        for(int ii=0; st[ii]; ii++){
            if(st[ii]=='a') a++;
            else if(st[ii]=='b') b++;
            else if(st[ii]=='c') c++;
            else if(st[ii]=='d') d++;
            else if(st[ii]=='e') e++;
            else if(st[ii]=='f') f++;
            else if(st[ii]=='g') g++;
            else if(st[ii]=='h') h++;
            else if(st[ii]=='i') i++;
            else if(st[ii]=='j') j++;
            else if(st[ii]=='k') k++;
            else if(st[ii]=='l') l++;
            else if(st[ii]=='m') m++;
            else if(st[ii]=='n') n++;
            else if(st[ii]=='o') o++;
            else if(st[ii]=='p') p++;
            else if(st[ii]=='q') q++;
            else if(st[ii]=='r') r++;
            else if(st[ii]=='s') s++;
            else if(st[ii]=='t') t++;
            else if(st[ii]=='u') u++;
            else if(st[ii]=='v') v++;
            else if(st[ii]=='w') w++;
            else if(st[ii]=='x') x++;
            else if(st[ii]=='y') y++;
            else if(st[ii]=='z') z++;
            else if(st[ii]=='A') A++;
            else if(st[ii]=='B') B++;
            else if(st[ii]=='C') C++;
            else if(st[ii]=='D') D++;
            else if(st[ii]=='E') E++;
            else if(st[ii]=='F') F++;
            else if(st[ii]=='G') G++;
            else if(st[ii]=='H') H++;
            else if(st[ii]=='I') I++;
            else if(st[ii]=='J') J++;
            else if(st[ii]=='K') K++;
            else if(st[ii]=='L') L++;
            else if(st[ii]=='M') M++;
            else if(st[ii]=='N') N++;
            else if(st[ii]=='O') O++;
            else if(st[ii]=='P') P++;
            else if(st[ii]=='Q') Q++;
            else if(st[ii]=='R') R++;
            else if(st[ii]=='S') S++;
            else if(st[ii]=='T') T++;
            else if(st[ii]=='U') U++;
            else if(st[ii]=='V') V++;
            else if(st[ii]=='W') W++;
            else if(st[ii]=='X') X++;
            else if(st[ii]=='Y') Y++;
            else if(st[ii]=='Z') Z++;
        }
        int ar[52] {A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z};
        sort(ar,ar+52);
        int mx = ar[51];
        if(mx != 0){
            if(A==mx) cout << "A";
            if(B==mx) cout << "B";
            if(C==mx) cout << "C";
            if(D==mx) cout << "D";
            if(E==mx) cout << "E";
            if(F==mx) cout << "F";
            if(G==mx) cout << "G";
            if(H==mx) cout << "H";
            if(I==mx) cout << "I";
            if(J==mx) cout << "J";
            if(K==mx) cout << "K";
            if(L==mx) cout << "L";
            if(M==mx) cout << "M";
            if(N==mx) cout << "N";
            if(O==mx) cout << "O";
            if(P==mx) cout << "P";
            if(Q==mx) cout << "Q";
            if(R==mx) cout << "R";
            if(S==mx) cout << "S";
            if(T==mx) cout << "T";
            if(U==mx) cout << "U";
            if(V==mx) cout << "V";
            if(W==mx) cout << "W";
            if(X==mx) cout << "X";
            if(Y==mx) cout << "Y";
            if(Z==mx) cout << "Z";
            if(a==mx) cout << "a";
            if(b==mx) cout << "b";
            if(c==mx) cout << "c";
            if(d==mx) cout << "d";
            if(e==mx) cout << "e";
            if(f==mx) cout << "f";
            if(g==mx) cout << "g";
            if(h==mx) cout << "h";
            if(i==mx) cout << "i";
            if(j==mx) cout << "j";
            if(k==mx) cout << "k";
            if(l==mx) cout << "l";
            if(m==mx) cout << "m";
            if(n==mx) cout << "n";
            if(o==mx) cout << "o";
            if(p==mx) cout << "p";
            if(q==mx) cout << "q";
            if(r==mx) cout << "r";
            if(s==mx) cout << "s";
            if(t==mx) cout << "t";
            if(u==mx) cout << "u";
            if(v==mx) cout << "v";
            if(w==mx) cout << "w";
            if(x==mx) cout << "x";
            if(y==mx) cout << "y";
            if(z==mx) cout << "z";
            cout << " " << mx << endl;
        }
    }
    return 0;
}
